### ISSUE TITLE
VirtualBox Version 5 Not Supported

### ISSUE THREAD

**Issue by jsingle** [gamechanger/dusty#383]
It seems like boot2docker does not yet support VirtualBox 5 (released 7/9/15).  Specifically, we are observing that creating a new boot2docker VM with `boot2docker init` does not work.  There is an open issue on the boot2docker project regarding this compatibility here: https://github.com/boot2docker/boot2docker/issues/979

**Comment by nikolay** [comment]
:+1:

**Comment by thieman** [comment]
[boot2docker 1.7.1](https://github.com/boot2docker/boot2docker-cli/releases/tag/v1.7.1) has fixed the compatibility issue with VBox 5, hooray. If you're having this problem and come across this issue, make sure your boot2docker is up-to-date.

**Comment by sdaitzman** [comment]
:+1: :smile:
