### ISSUE TITLE
Installation not working with OSX 10.11 (El Capitan)

### ISSUE THREAD

**Issue by amenophis** [gamechanger/dusty#402]
Seems El Capitan disallow writing in ```/System/Library/LaunchDaemons```
Not really tested, but install works with this script:

```bash
set -e

# This is set by Jenkins during release
release='0.2.1'

function bold_echo {
    echo -e "\033[1m$1\033[0m"
}

bold_echo "Downloading dusty binary"
curl -L https://github.com/gamechanger/dusty/releases/download/$release/dusty > /usr/local/bin/dusty
chmod +x /usr/local/bin/dusty
bold_echo "Authenticating as super user... needed to setup daemon"
bold_echo "Resetting dusty daemon"
curl -L -o ~/Library/LaunchAgents/org.gamechanger.dusty.plist https://raw.githubusercontent.com/gamechanger/dusty/$release/setup/org.gamechanger.dusty.plist
launchctl unload ~/Library/LaunchAgents/org.gamechanger.dusty.plist
bold_echo "Testing dusty daemon's preflight..."
sudo -H dusty -d --preflight-only || (bold_echo "Preflight failed; not loading daemon"; exit 1)
bold_echo "Loading dusty daemon"
launchctl load ~/Library/LaunchAgents/org.gamechanger.dusty.plist
````

**Comment by thieman** [comment]
Welp. This is obnoxious. http://stackoverflow.com/questions/30768087/restricted-folder-files-in-os-x-el-capitan

Using the user's Library folder is probably okay, anyone foresee any problems with that? @jsingle @paetling

**Comment by thieman** [comment]
Actually writing it to the user's folder makes no sense since it's a root-owned daemon. I wonder if we can put it in root's home folder version of Library?

**Comment by jsingle** [comment]
I think you want it in `/Library` not in `~/Library`

**Comment by thieman** [comment]
@amenophis Do you know whether `/Library` is writable? We don't have anyone with 10.11 installed right now, unfortunately.

**Comment by confucious** [comment]
```jhsu@alphonse:~$ ls -ld /Library
drwxr-xr-x+ 64 root  wheel  2176 Jun  8 16:59 /Library
```

**Comment by thieman** [comment]
@confucious So does that mean it's writable? Not sure what I'm looking for here.

**Comment by confucious** [comment]
Yeah, never mind that last comment. I tried editing a file in /Library/LaunchDaemons and I was able to. 
`sudo vi /Library/LaunchDaemons/test.txt`

**Comment by confucious** [comment]
```
jhsu@alphonse:~$ ls -ldO /System/Library/LaunchDaemons/
drwxr-xr-x  287 root  wheel  restricted 9758 Jul  8 14:56 /System/Library/LaunchDaemons/
jhsu@alphonse:~$ ls -ldO /Library/LaunchDaemons/
drwxr-xr-x  9 root  wheel  - 306 Jul 13 12:23 /Library/LaunchDaemons/
```

**Comment by thieman** [comment]
Cool, let's move to using `/Library` then. We'll need to be considerate of people who already have it installed in the previous location.

**Comment by amenophis** [comment]
Seems the better solution is ```/Library``` according to some reading i've done !

**Comment by thieman** [comment]
Thanks @amenophis, this fix will roll out with the install script for 0.2.2.
