### ISSUE TITLE
dusty makes assumptions about nginx conf

### ISSUE THREAD

**Issue by zacharym** [gamechanger/dusty#413]
During `setup` Dusty tries to find the user's nginx includes dir so that it can set the config var `nginx_includes_dir`. This get's used to set the path of the file where dusty will write nginx conifg. 

Unless run with the `--nginx_includes_dir` flag, Dusty assumes the users `nginx.conf` file has the line `include servers/*;` If the user has modified this to be something else such as `include servers/*.conf;` Dusty incorrectly parses the line and sets the config variable `nginx_includes_dir` to be `.../servers/*.conf` rather than `.../servers/`. 

Everything proceeds normally until Dusty tries to modify the user's nginx at which point it tries to access the file `.../servers/*.conf/dusty.conf` which fails. 
```
Saving nginx config and ensure nginx is running
ERROR: [Errno 2] No such file or directory: '/usr/local/etc/nginx/servers/*.conf;/dusty.conf
```

I think we should either make the nginx config parsing smarter or make setup flow make it apparent to the user that they need to explicitly set the nginx_includes_dir if they have modified their `nginx.conf`

**Comment by thieman** [comment]
Closing this due to the Sarin Corollary: bugs which are deleted do not require fixing. None of the Mac nginx config stuff exists any more, it's all containerized.
