### ISSUE TITLE
Consider using docker-machine instead of boot2docker

### ISSUE THREAD

**Issue by rsperl** [gamechanger/dusty#418]
Since boot2docker is deprecated (https://github.com/boot2docker/boot2docker-cli#pending-deprecation), consider supporting docker-machine instead.

**Comment by thieman** [comment]
We'll definitely do this at some point. We made the decision to go with boot2docker to start with because Machine still has a big "this is a beta" warning and we didn't want the API to constantly change on us. https://docs.docker.com/machine/

**Comment by thieman** [comment]
If someone wanted to spend the time figuring out what the recent history of Machine is and whether their API seems to have mostly stabilized, we may be able to begin work on this.

**Comment by thieman** [comment]
This is looking even more attractive now that Toolbox bundles all of our dependencies (if we were to switch to Machine) into a single download. May be the time to move over.

![image](https://cloud.githubusercontent.com/assets/1414305/9229837/1dcf810e-40ed-11e5-93ae-8f4ef4c43bc2.png)

**Comment by thieman** [comment]
It looks like in practice their changelog has been pretty stable, not a lot of breaking changes. https://github.com/docker/machine/blob/master/CHANGELOG.md

I think it'd make sense to prioritize this after NFS. The earlier we make the move, the less painful it'll be.

**Comment by AnneTheAgile** [comment]
Not sure others' experience, but on a non-latest mac and latest windows, boot2docker was never a good experience for me. I never got it working right. I will try Docker machine.
ty for your PyGotham talk!
AnneTheAgile
