### ISSUE TITLE
dusty sync growl notifications

### ISSUE THREAD

**Issue by artburkart** [gamechanger/dusty#432]
I'm not accustomed to having to wait a few seconds for my interpreted file changes to propagate to my docker container. It confuses me when I'm developing. 

Maybe it would be possible to add growl support via [gntp](https://pypi.python.org/pypi/gntp), so I know when to expect my changes to exist.

If you think the idea makes sense and could point me in the right direction, I'd be happy to try and hook it in :)

Cheers

**Comment by thieman** [comment]
We actually had this functionality built in with earlier builds, here's the PR where I killed it: https://github.com/gamechanger/dusty/pull/177/files

The issue we saw was that it was impossible for Dusty to know enough about the user's intent to intelligently issue notifications without spamming the user with stuff they didn't care about. It's possible we could revisit this functionality with a more flexible and customizable notification system, but I'm not sure off the top of my head how that would work.

I think the developers at GameChanger who have automated their Dusty workflow have built [terminal-notifier](https://github.com/julienXX/terminal-notifier) into their automation to give them context-aware messages on the Dusty commands they're running, so you can do something like `dusty sync my-repo && terminal-notifier 'Synced my-repo'`.

**Comment by artburkart** [comment]
`terminal-notifier` seems like a better solution. I think your conclusion was correct.

**Comment by thieman** [comment]
Cool, I'll go ahead and close this then.
