### ISSUE TITLE
Prototype NFS for file sharing

### ISSUE THREAD

**Issue by thieman** [gamechanger/dusty#442]
`rsync` is a big improvement over VBox shared folders, but it still takes a second or two to sync changes over, and it gets worse when your app uses a bunch of libs. We may be able to get the performance of rsync and the immediacy of shared folders by using NFS.

**Comment by jsingle** [comment]
NFS investigation uncovered https://github.com/boot2docker/boot2docker/issues/1022, which would seem to make performance unacceptable until we can resolve it

**Comment by jsingle** [comment]
We've built a release candidate https://github.com/gamechanger/dusty/releases/tag/0.5.0-RC1 which uses NFS instead of rsync for repos.

**Comment by thieman** [comment]
This made it out in 0.5.0.
