### ISSUE TITLE
Destructive rsync breaking `once` installs with Node.js

### ISSUE THREAD

**Issue by thieman** [gamechanger/dusty#452]
Report from @inlinestyle. The destructive rsync command introduced in `0.3.0` tends to break apps written in languages which write to their own source directories during setup or runtime. Node.js is one such language, as the typical workflow involves running an `npm install` which installs dependencies into a `node_modules` directory in the app's source directory. This directory will get deleted by the next rsync operation on that repo.

We need to fix this either by moving to a bidirectional sync model (#442) or adding a mechanism to exclude paths from destructive rsync.

**Comment by inlinestyle** [comment]
:+1:

**Comment by thieman** [comment]
Closing now that 0.5.0 with NFS has been released. This removes the destructive rsync on source folders, which should eliminate this issue.
