### ISSUE TITLE
Small issue with the help documentation for tests

### ISSUE THREAD

**Issue by harrisosserman** [gamechanger/dusty#462]
When you run `dusty test -h` the output shows that the suggested way of running a test is like this:

`Usage:
  test [options] <app_or_lib_name> [<suite_name>] [<args>...] [--recreate] [--no-pull]`

However, if someone wants to use `--recreate`, he/she should use it after typing `dusty test` but not after `dusty test <app_or_lib> <suite>`.  I think you guys should change the Usage line to read like this:

`Usage:
  test [options][--recreate] <app_or_lib_name> [<suite_name>] [<args>...] [--no-pull]`

Small request that would clarify things for dusty people

**Comment by thieman** [comment]
THANKS HARRIS
