### ISSUE TITLE
RFC: `dusty assets` to get user keys/secrets into containers

### ISSUE THREAD

**Issue by thieman** [gamechanger/dusty#470]
Original request from user `abooth` in the Slack org. Currently, it is very difficult to create a Dusty app which relies on a user-provided secret, for example a private SSH key. The options are limited: you can bake the secret into the image (if and only if you're using a private Docker registry), or you can have the users manually `dusty cp` their secret into the container once it's created. Both of these leave a lot to be desired.

This is probably a fairly common thing to want to do, as you could create an app which installs packages from a private package manager or private GitHub repo. Dusty should support this flow in a way that doesn't require private Docker registries or manual user intervention.

My proposal is to add a concept called an `asset` which would allow an app or library spec to specify an asset which should be provided by the user and made available at a specific path inside the container. We may also need to add these spec options to the testing containers.

```yaml
# inside an app or lib spec
assets:
  - name: GITHUB_KEY
    path: /etc/keys/id_github.rsa
```

In addition to this spec change, we would add an `assets` subcommand to the CLI. This would allow users to register assets at a local filepath on their Mac. Something like:

```
dusty assets register GITHUB_KEY ~/.ssh/my_github_key.rsa
```

We would need standard lifecycle management around these assets.

Finally, `dusty up` should check the required assets for the apps and libs that are active and throw an error (before trying to start anything) if any required assets have not been registered.

The details of keeping the assets up-to-date inside the VM may be drastically changed by #442, which is currently in progress. It may make sense to hold off on implementing this until NFS is completed, but we can talk out the design now.

**Comment by jsingle** [comment]
I think it's worth talking about whether this should be a rsync thing or a NFS thing.  Rsync would be less complex, but the assets would only update on `up` or `restart`
