### ISSUE TITLE
tutorial failed

### ISSUE THREAD

**Issue by udibr** [gamechanger/dusty#498]
I tried to follow the instructions on dusty tutorial.
According to [boot2docker](https://github.com/boot2docker/osx-installer/releases) it  is deprecated.
It said to install [Docker Toolbox](https://www.docker.com/toolbox) which I did.
I also tried to install latest version of boot2docker anyway.
I managed to advance with the tutorial until I received an error when running 
`dusty status` and when running `dusty up`

**Comment by paetling** [comment]
If you install boot2docker 1.7.1 Dusty should work. We currently still only support boot2docker, so you will need the above version.  
Also if you could paste any error messages you are getting that would be great.  
I will open a new issue for switching to Docker Machine.

**Comment by paetling** [comment]
Also feel free to reach out for installation help at our slack org: https://dusty-slackin.herokuapp.com/

**Comment by udibr** [comment]
I tried to install 1.7.1 and got an error when running `dusty status` for first time in the [hello-world](https://dusty.readthedocs.org/en/stable/getting-started/hello-world/) page
 
```
dusty status
ERROR: Command '['boot2docker', 'shellinit']' returned non-zero exit status 1
```

**Comment by udibr** [comment]
Looks like I had an old version of docker. Doing the following cleaned everything:

```
boot2docker destroy
boot2docker download
boot2docker init
boot2docker start
$(boot2docker shellinit)
docker ps
```
