### ISSUE TITLE
Boot2docker is deprecated. Need to Switch to Docker Machine

### ISSUE THREAD

**Issue by paetling** [gamechanger/dusty#499]
https://github.com/boot2docker/osx-installer/releases.  We need to switch to using the new recommended vm for docker - [Docker Machine](https://docs.docker.com/machine/)

**Comment by thieman** [comment]
The *installer* is officially deprecated in favor of Toolbox. The status of the projects remains as it was before, boot2docker is on the way out, Machine is replacing it but is still currently "in beta". https://docs.docker.com/machine/

Closing this in favor of #418 which is already covering moving to Machine.
