### ISSUE TITLE
Can we bundle Compose with our binary?

### ISSUE THREAD

**Issue by thieman** [gamechanger/dusty#500]
This would be beneficial for two reasons:

1. Fewer installation dependencies to get going with Dusty
1. We know exactly which version of Compose we'll be running against and can test accordingly, reducing risk of failure

Compose tends to add some pretty nice new features with each release, but we need to either specify a minimum version or bundle the binary if we expect to be able to use them.

**Comment by jsingle** [comment]
I like this idea.  Compose is 5MB though, so it would double our binary size.

**Comment by jsingle** [comment]
The downside to doing this is that people can't use a new version of compose until we cut a new dusty release with the new compose version, and they upgrade dusty

**Comment by thieman** [comment]
Spiking this, dependencies should be less of an issue with Toolbox.
