### ISSUE TITLE
chef script for prereqs?

### ISSUE THREAD

**Issue by AnneTheAgile** [gamechanger/dusty#501]
hi, would it be possible to share your chef scripts that you use to get a mac into a useable state for installing dusty? 

This might help with several things, including ports to linux and windows.
ty!
AnneTheAgile

**Comment by thieman** [comment]
Dusty doesn't have too many requirements on the Mac side, so we haven't needed to write up any sort of scripting to handle it. Everything you need to run should be on the [installation page](https://dusty.readthedocs.org/en/stable/installation/).

Basically, you need to make sure `boot2docker` and `docker-compose` are installed on your Mac, then Dusty should be able to install and run properly. If Dusty detects that any of its dependencies are missing when you try to install it, it'll fail and let you know what's wrong.

**Comment by thieman** [comment]
I'm going to go ahead and close this, please re-open if you've got any follow-up questions.
