### ISSUE TITLE
Minor errors in tutorial

### ISSUE THREAD

**Issue by udibr** [gamechanger/dusty#502]
In [installation](https://dusty.readthedocs.org/en/stable/installation/) the boot2docker should link to the last working version (1.7.1?)

The output of `dusty bundles list` in [getting started](https://dusty.readthedocs.org/en/stable/getting-started/) is out of date

In [getting started](https://dusty.readthedocs.org/en/stable/getting-started/) The markdown for working with `dusty-example-specs.git` locally is corrupted

In [hello-world](https://dusty.readthedocs.org/en/stable/getting-started/hello-world/) the output of `dusty bundles list` after activation of hello-world should show it activated with a big X mark

**Comment by thieman** [comment]
Thanks for the report! The last three are definitely bugs. We could maybe link directly to the release page for boot2docker, though for now we are recommending installing the dependencies through brew. Did installing through brew give you issues?

**Comment by udibr** [comment]
brew worked great.
I suggest adding the VM/docker cleanup steps to a troubleshotting section of the install/tutorial:

```
boot2docker destroy
boot2docker download
boot2docker init
boot2docker start
$(boot2docker shellinit)
docker ps
```
