### ISSUE TITLE
Repos which are specified with `https:` or `file:` cannot be mounted in 0.4.0

### ISSUE THREAD

**Issue by jsingle** [gamechanger/dusty#517]
Because Docker Compose uses colons to parse the output of a mount command, repos that are specified with a colon will not be parsed correctly.

This will be fixed in the next release (and is fixed in 0.5.0-RC1)

**Comment by thieman** [comment]
@jsingle If this is fixed in the RC then shouldn't this issue be closed?

**Comment by jsingle** [comment]
If that's the protocol then yes, good point.  I will make sure it's in the changelog
