### ISSUE TITLE
Can't name apps or services `nginx`

### ISSUE THREAD

**Issue by jsingle** [gamechanger/dusty#530]
This conflicts with naming of dusty's nginx for internal use, basically clobbering it.  Discovered by @melkorm 

The fix here should probably just be to add validation preventing apps and services from being named nginx.  Currently it's way to hard to tell what's actually going on

**Comment by thieman** [comment]
We should maybe change the nginx that Dusty uses to a name that'd be basically impossible to conflict with, like `dustyInternalNginx` or something

**Comment by melkorm** [comment]
@thieman I was thinking about the same solution and name for this! There is a little chance someone will use this name plus adding a validation would be nice to.

**Comment by jsingle** [comment]
Cool I like that idea
