### ISSUE TITLE
Specifying port or user in SSH repo path mangles local filepaths

### ISSUE THREAD

**Issue by thieman** [gamechanger/dusty#539]
Original report from @torbjornvatn on Slack. When specifying a remote repo with a path like `ssh://user@git.domain.com:7999/path/to/repo`, Dusty's path parsing comes up with `7999/path/to/repo` as the folder in which the repo should be stored inside `/etc/dusty/repos`. This causes various failures downstream where we end up looking for the files in the wrong place.

There also seem to be issues with specifying the `user` part of this URL. When I clone a repo with the spec `ssh://git@github.com:22/gamechanger/gcweb`, Dusty ends up sticking the contents of that repo at `/etc/dusty/repos/git@github.com`, without bothering to create any subfolders within that dir.

So, various critical problems. :smile:

**Comment by torbjornvatn** [comment]
## local repo
when add a ```repo: path/to/local/repo``` to ```apps/app1.yml``` and that local repo has a .git/config url of the form mentinoned above i get this error 
```bash 
ERROR: 'Error when fetching: fatal: unable to auto-detect email address (got 'root@torbjorns-mac.(none)')' returned with exit code 2
```

## remote repo
if I on the other hand use adds the ssh url directly to the repo setting I get this this 
```bash 
ERROR: 'git clone -v ssh://git@git@git.domain.com:7999/path/to/repo.git /etc/dusty/repos/7999/path/to/repo.git' returned with exit code 128
stderr: 'Cloning into '/etc/dusty/repos/7999/path/to/repo.git'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
