### ISSUE TITLE
Capitalization issue with NFS and HFS

### ISSUE THREAD

**Issue by jsingle** [gamechanger/dusty#547]
Currently, if you incorrectly capitalize a local path to a dusty repo, HFS on your mac will treat it fine, since HFS is case insensitive.  However NFS will fail to mount the repo if capitalization is not correct (in your `/etc/exports`).

To avoid this, just make sure your capitalization is the same as what HFS prefers.

We'll investigate building a better solution into Dusty.

**Comment by thieman** [comment]
An example of this is trying to override a repo inside your `/Users` directory and forgetting to capitalize the `U`, ending with an override like `/users/travis/my-repo`.
