### ISSUE TITLE
Trouble with /private/var/root/.ssh/known_hosts when using ssh:// repos

### ISSUE THREAD

**Issue by torbjornvatn** [gamechanger/dusty#554]
When i run `dusty up ` with a repo defined as `ssh://git@git.doman.com:7999/path/to/repo` I get this error message `ERROR: 'Error when fetching: fatal: Could not read from remote repository.' returned with exit code 2`

However, if I go to `/etc/dusty/repos/path/to/repo` and run `sudo git pull` I get the `The authenticity of host '[git.domain.com]:7999 ([xx.xx.xx.xx]:7999)' can't be established.... Are you sure you want to continue connecting (yes/no)?` question. If I confirm the host is added to `/private/var/root/.ssh/known_hosts` and `dusty up` works just fine. Unfortunately the known_hosts entry disappears when I restart my mac. (and it's not exactly ideal that I have to go through this procedure every time I restart) 

Can this be fixed any way, so that dusty's git pull uses my known_hosts file located in `$HOME/.ssh/known_hosts`?

**Comment by thieman** [comment]
We manually ensure that `github.com` is added to the root's known hosts during preflight. We don't do anything for private hosts currently, which we could consider doing.

We could possibly use another user's known hosts file, but we're doing the SSH operations as root, so I'm not sure how feasible that is.

It *should* be sufficient to do what you've done to manually add the domain as a known host for the root user. I have no clue what could be resetting your known hosts file on reboot. If you can diagnose that and stop it, manually adding the host should be permanent and you should stop having issues.

**Comment by torbjornvatn** [comment]
I could use this workaround for now as I'm testing Dusty, but it would be a bit of a hurdle if the rest of my team should start using it for their daily development workflow.

How about copying all entries for the `~/.ssh/known_hosts` file of the user issuing the dusty command, or at least all entries containing `.*git.*` ?

**Comment by thieman** [comment]
This is probably a bit dodgy from a security perspective, but we could either try to convince Git to ignore the hosts check (not sure if that's possible with our Git driver) or just parse all hosts from the repo specs and make sure they're all added. I'd prefer a fully automatic solution.

**Comment by jsingle** [comment]
I think the last option, where we parse hosts from specs and add them, is doable, but might end up necessitating some janky python code (running subprocesses that do `ssh-keyscan`, etc).  I'm doubtful that we can tell our git commands to ignore the hosts check.  I also agree that just copying known hosts from user to root is a little sketchy.

**Comment by torbjornvatn** [comment]
I guess this would be a problem for people using bitbucket etc. as well, so an automatic solution would have been nice :pray:

**Comment by jsingle** [comment]
I think we've decided to have Dusty automatically add any hosts you specify in your specs to root's `known_hosts`.  This will probably get implemented next week

**Comment by torbjornvatn** [comment]
:grinning:

**Comment by jsingle** [comment]
Turns out that url parsing in python is hard :(
