### ISSUE TITLE
Dusty status error

### ISSUE THREAD

**Issue by FabienMotte** [gamechanger/dusty#568]
When I run the command `dusty status`, I get this error :
```
ERROR: Command '['docker-machine', 'status', 'dusty']' returned non-zero exit status 1
```

Dusty version : **0.6.0-RC2**.

Seems to be related to the fact that Dusty now use Docker Machine and try to run **`docker-machine status`** command on the VM instead of the `dusty status` command.

Thank you !

**Comment by thieman** [comment]
Could you please provide the output of `dusty dump` (if it returns successfully) in a [gist](gist.github.com) and any relevant output from the log at `/var/log/dusty.log`? Also, have you gotten `dusty up` to run successfully using Docker Machine?

**Comment by FabienMotte** [comment]
Output of `dusty dump` command : https://gist.github.com/FabienMotte/6bb6b54f4ab0ad948a52

Dusty logs file (`/var/log/dusty.log`) : https://gist.github.com/FabienMotte/fa69c08f3d46de662462

Yes, the command `dusty up` is working fine, I can access to local.flaskone.com for example (in the case of the `dusty-flask-example` bundle).

**Comment by thieman** [comment]
Based on all the errors about docekr-machine commands not existing in your log, I think this may be that you're running an older version of Docker Machine than what we support. It says that `docker-machine version` isn't a command, but could you either try figuring out what version you're running or upgrade yourself to the latest Docker Machine version and see if that fixes the issue?

**Comment by FabienMotte** [comment]
Great ! I was using an older version of Docker machine (0.3.1), all is working fine now with the last version (0.4.1), thank you for your quick answers ! :smile:
