### ISSUE TITLE
Tests can fail when app under test is a substring of another app

### ISSUE THREAD

**Issue by thieman** [gamechanger/dusty#587]
Report from @tleach. Consider two applications, `alpha` and `alphabet`. Under the following conditions, `dusty test alpha <suite>` will fail:

1. An intermediate test image `dusty/test_alphabet` already exists for the longer app. This is created whenever you run `dusty test alphabet <suite>`.
1. The `alpha` app has never been tested, so a corresponding intermediate test image called `dusty/test_alpha` does *not* exist.
1. Running `dusty test alpha <suite>` will erroneously believe the intermediate testing image for `alpha` already exists and will not attempt to create it. This will fail, probably with the message `Error: image dusty/test_alpha:latest not found`

The issue is with the `image_exists` check in `dusty.system.docker.testing_image`. This should be an exact check, not an `in` check. Also worth checking whether we are doing a similarly loose check anywhere else.

**Comment by paetling** [comment]
@thieman not sure this is an actual issue.  we are using `in` in `image_exists` because `image['RepoTags']` is a list.  So we are not using string contains.  I also tried to reproduce this issue with an app named `test` and an app named `test1` and it did not reproduce the behavior described above.

**Comment by thieman** [comment]
I'm guessing this was fixed by this recent commit, but this issue wasn't closed. https://github.com/gamechanger/dusty/commit/96a1e78879f6b5234e6c7d83f53aa11f6fe47ab5
