### ISSUE TITLE
Avoid installation via curl & pipe

### ISSUE THREAD

**Issue by sporkmonger** [gamechanger/dusty#610]
Could we maybe try to push releases to package management, particularly since you've made your canonical install script unusually difficult to vet?

Inside that install script, you're downloading a bunch of stuff which doesn't get verified before exec. I count at least 4 separate sources of potentially malicious executable code, none of which is ever checked against known signatures, with the preflight check being the most difficult to vet. At least with Vagrant I can get it from a trusted source that signs their packages.

**Comment by thieman** [comment]
Just to make sure we are on the same page before discussing further, I think there are 3 separate downloads that could be verified:

1. The install script itself
2. The `dusty` binary that the install script downloads (the first `curl` command)
3. The plist file that the install script downloads (the second `curl` command)

The preflight check is run via the daemon you just downloaded and, assuming the daemon itself was not compromised, does not download any additional code (it just checks whether you have necessary dependencies installed). I don't see why the preflight would add any additional attack surface.

I think my preferred way to address this would be to do the following:

1. Add a checksum for the `install.sh` script itself to the Installation docs
2. Have the install script verify checksums of the binary and plist

This would require a tiny amount of extra automation in our Jenkins job but it doesn't sound particularly onerous.

I'm not a huge fan of Homebrew but that could potentially be an option? Though I prefer having full control over our releases and not having to rely on external registries. It should also be noted that Dusty has functionality to upgrade its own binary, I'm not sure how that might be reconciled with a package manager that expects to be able to track versions. Do you have any insight there that might be helpful?

**Comment by thieman** [comment]
I guess the real issue is that you seem to not consider GitHub a trusted source? Everything we have now is downloaded from GitHub, and if our GitHub repo was compromised then none of the stuff I just talked about would matter anyway.

**Comment by sporkmonger** [comment]
OK, let's say I audit your code, right? I want to make sure that the code I'm installing is the same code I've already audited. There's currently no way for me to use the install script you've provided in that kind of an environment because the install script itself loads new code without verifying it. If you absolutely must go the route of install via curl, then publish a SHA-256 hash of the script and modify your install command to short circuit on hash mismatch. Then embed SHA-256 hashes of all the included executables, checking each one before running. This is, however, hopelessly redundant because literally every good package manager essentially already does this by bundling everything together and hashing the combined package. Installing this way just unnecessarily duplicates work while making your update mechanism more complicated.

Trust is not about "I trust GitHub" or "I trust X, Y, or Z". It's more like "I know an audit of this code was done by someone who knows their shit, that audit was done on the package with hash X and the software I just downloaded has hash X therefore I trust that I have the same code that was audited by aforementioned trusted party." The install mechanism you've opted for makes the latter essentially impossible and thus Dusty is really hard to use in any environment where security matters.

**Comment by jsingle** [comment]
Unfortunately mac doesn't have great package managers... we did look into using homebrew at one point, but decided against it for reasons that I don't remember off the top of my head

**Comment by sporkmonger** [comment]
Homebrew is far more reasonable than what's being done right now...

**Comment by thieman** [comment]
I think we could look into using Homebrew again, specifically the cask method where we provide binaries rather than installing from source (which might have been our gripe the first time around).

**Comment by sporkmonger** [comment]
I would have recommended cask in any case. IIRC vagrant comes in a cask too.

**Comment by thieman** [comment]
@sporkmonger If you have any other insight or experience w.r.t Homebrew or any other options I'm sure it would be helpful. I understand where you're coming from with your request and I don't mean to come across as dismissive or unreceptive. Trusted install wasn't a priority for us when we first rolled out Dusty but I think everything you're saying makes sense.

**Comment by sporkmonger** [comment]
TBH, happy to put a cask together for you to get the ball rolling, but I probably don't have the time to maintain it, so it'd be something I'd be handing off to you guys when I'm done.

**Comment by sporkmonger** [comment]
So I've gone and thrown one together. It works with the releases you have as-is. However, it's noteworthy that the installer script stanzas are way, way more verbose and involved than necessary because you're publishing a naked binary instead of a binary tarball. If you published a binary tarball, you wouldn't need the `chmod +x` step in either the canonical `install.sh` script or the cask installer stanzas, since tarballs will preserve the execute bit, plus you get both the binary and the launchd plist file in a single container, which means you can verify both at the same time with the same sha256 hash, which eliminates 90% of the cruft in this cask.

[dusty.rb](https://files.zenhub.io/56943c05868eed7b6ccc9e96)

**Comment by thieman** [comment]
@sporkmonger This is a great help, thanks. I'll try to push this over the line at least to the point where we have a single release in brew, hopefully this weekend.

**Comment by sporkmonger** [comment]
Awesome, really appreciate it.

**Comment by sporkmonger** [comment]
Here's what it'd look like if you published a binary tarball containing both the binary and the plist:

[dusty.rb](https://gist.githubusercontent.com/sporkmonger/2f98413e0ace6a3584d0/raw/72c86736641fa54c3d8e8560890f18aff3cbba87/dusty.improved.rb)

**Comment by thieman** [comment]
Much nicer, we'll for sure do that.

**Comment by thieman** [comment]
@sporkmonger Our cask recipe was just merged with the version we released today, 0.6.5. Could you please verify whether that's working for you and meets the needs of this issue?

We still have some cleanup work to do around documentation and our release process to maintain the cask going forward, so I think I'll leave this open until that's all taken care of.

**Comment by adityadalal924** [comment]
Hi, I'm one of the maintainers of Homebrew Cask.

`brew cask install dusty` is now available. (https://github.com/caskroom/homebrew-cask/pull/16966)

FYI, As the Cask just calls a script from the downloaded `.tar.gz to finish setup`, everything should now be fully auditable (no more `curl`-ing out.

**Comment by thieman** [comment]
Thanks @adityadalal924!

**Comment by thieman** [comment]
Made minor doc changes to Installation and Contributing sections. They won't show up in `stable` on RTD until we do another release, but they'll make it out there before too long.

**Comment by thieman** [comment]
Going to close this for now, please reopen if you have any other concerns
