### ISSUE TITLE
Dusty should cleanup unused volumes and images

### ISSUE THREAD

**Issue by paetling** [gamechanger/dusty#622]
Yesterday I ran into a problem where I ran out of disk space on my Virtualbox dusty vm.  The problem seems to be that I had a bunch of left over containers and images from what I assume is the dusty testing process.   I used the following command to cleanup this leftover junk:
```
docker rm $(docker ps -aq)
docker rmi $(docker images -q)
```

This seems like something that dusty should be handling / cleaning up itself.  

Thoughts?

**Comment by thieman** [comment]
Is this a dupe of https://github.com/gamechanger/dusty/issues/603?

**Comment by paetling** [comment]
Seems to be very similar yes.  Do we handle removing containers correctly?  Both were issues for me.
