### ISSUE TITLE
Should dusty stop the VM on every `dusty up` command

### ISSUE THREAD

**Issue by paetling** [gamechanger/dusty#623]
So originally when we were building this system with boot2docker there was only one VM.  We took the stance that we did not own the VM so we did not want to stop / adversely affect that VM.  With the switch over to docker-machine, this is less of an issue.  We specifically create a VM with our dusty namespace.  It seems like we basically own this VM.    

On top of this, Dusty sometimes runs into bad network, unkillable containers, and other strange issues that are not fixed by current `dusty up` command.  With these two points in mind, why not have dusty stop the vm each time on dusty up and then restart it?  The code change would be minimal.  The real impact could be on dusty up time, especially for smaller dusty configs, but we do not have good insights into this timing.  The consistency benefits could be very large though.

What are your thoughts @thieman @jsingle ?

**Comment by thieman** [comment]
Restarting the VM takes ages, and it's a nuclear option that prevents us from actually understanding or fixing any underlying issues (to the extent Dusty has the power to do so). -1

This would make more sense in the `dusty doctor` command we've talked about before than in `up` which is a general command that gets run rather frequently, and the vast majority of those runs would get no benefit from a VM restart.

**Comment by thieman** [comment]
@paetling Motion to close

**Comment by paetling** [comment]
:+1:
