### ISSUE TITLE
Confusion about repo URLs

### ISSUE THREAD

**Issue by mugli** [gamechanger/dusty#624]
First of all, dusty is godsend for using docker in OSX. Thanks for this.

I've had some confusions about repo urls (both for specs_repo and apps) while setting up dusty for the first time. 

**What format(s) worked:**
1. `github.com/gamechanger/dusty-example-specs`
2. `https://github.com/gamechanger/dusty-flask-example.git`

I haven't seen use of `no. 1` much anywhere else. It was hard to figure out that this'll work.
I had to use private repos so using `no. 2` was not an option.

**Didn't work:**
1. `git@github.com:gamechanger/dusty-example-specs.git`

This is probably most widely used format. Surprised to find this not working. 

I got this when trying `dusty repos update`:

```
Pulling latest updates for all active managed repos:
Updating managed copy of specs-repo before loading specs
ERROR: Git command failed. If you are trying to access a remote repository over SSH (e.g. GitHub), please make sure you have added your SSH key to the SSH agent using: ssh-add <SSH key filepath>.  If you specified to clone the repo using HTTP, the repo must be public; private repo access is only supported with ssh
ERROR: 'git clone -v ssh://git@git@github.com:gamechanger/dusty-example-specs.git /etc/dusty/repos/git@github.com:gamechanger/dusty-example-specs' returned with exit code 128
stderr: 'Cloning into '/etc/dusty/repos/git@github.com:gamechanger/dusty-example-specs'...
ssh: connect to host github.com:gamechanger port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
'
```

I've run `ssh-add <SSH key filepath>` before installing dusty, as mentioned in the docs.

Is this expected behavior or I'm missing something? Also couldn't find anything about specific url format in the docs.

**Comment by thieman** [comment]
Hi there, thanks for writing in. Always happy to help out someone who takes the time to spell out their issue clearly. :smile:

We do have examples of the three types of formats we definitely support in our docs in the App Specs and Lib Specs sections. If you look [here](http://dusty.readthedocs.org/en/stable/specs/app-specs/) under the `repo` block, you can see the two types you mentioned plus the absolute file path. There might be improvements we could make here in terms of both explaining how the first format works (uses SSH under the hood, so should work with private repos) and exposing this better to the user. I'd be happy to hear any suggestions you had for making this more clear.

In addition, I believe we currently support a fully specified SSH path per this issue: https://github.com/gamechanger/dusty/issues/539. This is necessary if you need to specify a user other than `git` or an SSH port other than `22`. We should verify whether this is working currently and add it to the docs. That's an oversight there, my apologies.

As for the `git@github.org/repo.git` form you give, I believe it should work if you tack `ssh://` on to the front of it to make it a fully specified SSH path. Do you think that would meet your needs?

**Comment by mugli** [comment]
My bad, missed the repo block [here](http://dusty.readthedocs.org/en/stable/specs/app-specs/). `dusty-example-specs` repo was so good I didn't have to take a look there. So I'm thinking maybe a comment in `dusty-example-specs` where specifying app repos will help future users? Also should be [here](http://dusty.readthedocs.org/en/stable/setup/) in `Specs Repo` block.

 Didn't know about adding `ssh://` trick also. Thanks for this. Is it possible for dusty to prepend it if not present? Because most of the time users will just copy git url from github and it is not there.
