### ISSUE TITLE
$http_host versus $host

### ISSUE THREAD

**Issue by morganjbruce** [gamechanger/dusty#662]
Having a touch of trouble with the generated nginx config and accessing my underlying Rails app, which is running on port 3005, with the Docker host forwarded as app.local.

At the moment, the `Host` header is set to `$host`, which Rails (at least this version) interprets as `app.local:80`, rather than `app.local:3005`.  This causes redirects to be incorrectly made to `app.local`, minus the port.

Would it be feasible to change this to use `$http_host`, which includes the port information?  I've tested this locally & it works; but I'm definitely not an Nginx expert so I'm less sure how it would affect other users.

**Comment by thieman** [comment]
Thanks for the report @morganjbruce, we'll look into it. Do you by chance have a public Dusty spec with a Rails app in it we could use to reproduce the problem? We're mostly Python people, light on Rails expertise.

**Comment by thieman** [comment]
@morganjbruce Nevermind, I'm able to reproduce with Flask. Great catch, thanks! Will roll a new RC out with this in a few minutes.

**Comment by thieman** [comment]
This is live in the latest RC, which you can get by running `dusty upgrade 0.7.1-RC7`

**Comment by morganjbruce** [comment]
Awesome, thanks!
